# Generated by Django 3.1 on 2020-08-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200815_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_use',
            new_name='fees_in_usa',
        ),
    ]
